Visualforce Field History is a visualforce component and apex classes for reading the rather cryptic and undocumented __History tables generated by salesforce for tracked field changes.

Currently it only supports custom objects, but the changes required to support standard objects shouldn't be too much extra work. If you care about it make an issue and I'll see about adding that support.

![](http://github.com/capeterson/Visualforce-Field-History/blob/master/screenshot.png)
